steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/utilitarian-bee-244108/asdasdasd', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/utilitarian-bee-244108/asdasdasd']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'test-cloud-run-service', '--image', 'gcr.io/utilitarian-bee-244108/asdasdasd', '--region', 'us-central1']
images:
- gcr.io/utilitarian-bee-244108/asdasdasd